GET http://localhost:3001/api/notes
###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Cool new important note",
  "important": true
}

###

PUT http://localhost:3001/api/notes/62e89cf7df643dac768b7a44
Content-Type: application/json

{
  "content": "I changed the note!",
  "important": false
}

###

DELETE http://localhost:3001/api/notes/62e8a675f610f09e2534617a
